"""phase 3: trading & journal models

Revision ID: 1f2cd9eda7fb
Revises: 65062af6dc3f
Create Date: 2026-08-28 23:02:02.663380
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1f2cd9eda7fb'
down_revision: str | None = '65062af6dc3f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tag_user_name')
    )
    op.create_table('balance_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('trading_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('comment', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trading_account_id'], ['trading_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trading_account_id', 'ts', name='uq_balance_account_ts')
    )
    op.create_index('ix_balance_account_ts', 'balance_snapshots', ['trading_account_id', 'ts'], unique=False)
    op.create_table('daily_statistics',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('trading_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('win_count', sa.Integer(), nullable=False),
    sa.Column('loss_count', sa.Integer(), nullable=False),
    sa.Column('be_count', sa.Integer(), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('gross_loss', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('expectancy', sa.Float(), nullable=True),
    sa.Column('best_trade', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('worst_trade', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('avg_win', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('avg_loss', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('r_sum', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('recalculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trading_account_id'], ['trading_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trading_account_id', 'day', name='uq_daily_account_day')
    )
    op.create_index('ix_daily_account_day', 'daily_statistics', ['trading_account_id', 'day'], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('trading_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('deal_ticket', sa.String(length=64), nullable=False),
    sa.Column('order_ticket', sa.String(length=64), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('profit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('swap', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('commission', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trading_account_id'], ['trading_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trading_account_id', 'deal_ticket', name='uq_deal_account_ticket')
    )
    op.create_index('ix_deals_account_time', 'deals', ['trading_account_id', 'time'], unique=False)
    op.create_table('deposits',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('trading_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trading_account_id'], ['trading_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deposits_account', 'deposits', ['trading_account_id'], unique=False)
    op.create_table('equity_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('trading_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('comment', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trading_account_id'], ['trading_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trading_account_id', 'ts', name='uq_equity_account_ts')
    )
    op.create_index('ix_equity_account_ts', 'equity_snapshots', ['trading_account_id', 'ts'], unique=False)
    op.create_table('monthly_statistics',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('trading_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('win_count', sa.Integer(), nullable=False),
    sa.Column('loss_count', sa.Integer(), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('gross_loss', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('recalculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trading_account_id'], ['trading_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trading_account_id', 'month', name='uq_monthly_account_month')
    )
    op.create_index('ix_monthly_account_month', 'monthly_statistics', ['trading_account_id', 'month'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('trading_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ticket', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('floating_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('sl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('tp', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trading_account_id'], ['trading_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trading_account_id', 'ticket', name='uq_position_account_ticket')
    )
    op.create_index('ix_positions_account', 'positions', ['trading_account_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('trading_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ticket', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('swap', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('commission', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('mae', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('mfe', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('mae_pct', sa.Float(), nullable=True),
    sa.Column('mfe_pct', sa.Float(), nullable=True),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('risk_amount', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('partial_closes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trading_account_id'], ['trading_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trading_account_id', 'ticket', name='uq_trade_account_ticket')
    )
    op.create_index('ix_trades_account_close_time', 'trades', ['trading_account_id', 'close_time'], unique=False)
    op.create_index('ix_trades_account_symbol', 'trades', ['trading_account_id', 'symbol'], unique=False)
    op.create_table('withdrawals',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('trading_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trading_account_id'], ['trading_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_withdrawals_account', 'withdrawals', ['trading_account_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('trading_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('trade_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('entry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('setup', sa.String(length=100), nullable=False),
    sa.Column('emotion_before', sa.String(length=30), nullable=False),
    sa.Column('emotion_during', sa.String(length=30), nullable=False),
    sa.Column('emotion_after', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('fear', sa.Boolean(), nullable=False),
    sa.Column('greed', sa.Boolean(), nullable=False),
    sa.Column('revenge', sa.Boolean(), nullable=False),
    sa.Column('fomo', sa.Boolean(), nullable=False),
    sa.Column('boredom', sa.Boolean(), nullable=False),
    sa.Column('discipline', sa.Integer(), nullable=False),
    sa.Column('rule_adherence', sa.Boolean(), nullable=False),
    sa.Column('reason_entry', sa.String(length=255), nullable=False),
    sa.Column('reason_exit', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=False),
    sa.Column('lesson', sa.String(length=1000), nullable=False),
    sa.Column('plan_match', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.ForeignKeyConstraint(['trading_account_id'], ['trading_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_journal_user_date', 'journal_entries', ['user_id', 'entry_date'], unique=False)
    op.create_table('psychology_entries',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('trading_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('journal_entry_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mood', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('focus', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['trading_account_id'], ['trading_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_psychology_user_ts', 'psychology_entries', ['user_id', 'ts'], unique=False)
    op.create_table('trade_tags',
    sa.Column('journal_entry_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tag_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('journal_entry_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_tags')
    op.drop_index('ix_psychology_user_ts', table_name='psychology_entries')
    op.drop_table('psychology_entries')
    op.drop_index('ix_journal_user_date', table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index('ix_withdrawals_account', table_name='withdrawals')
    op.drop_table('withdrawals')
    op.drop_index('ix_trades_account_symbol', table_name='trades')
    op.drop_index('ix_trades_account_close_time', table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_positions_account', table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_monthly_account_month', table_name='monthly_statistics')
    op.drop_table('monthly_statistics')
    op.drop_index('ix_equity_account_ts', table_name='equity_snapshots')
    op.drop_table('equity_snapshots')
    op.drop_index('ix_deposits_account', table_name='deposits')
    op.drop_table('deposits')
    op.drop_index('ix_deals_account_time', table_name='deals')
    op.drop_table('deals')
    op.drop_index('ix_daily_account_day', table_name='daily_statistics')
    op.drop_table('daily_statistics')
    op.drop_index('ix_balance_account_ts', table_name='balance_snapshots')
    op.drop_table('balance_snapshots')
    op.drop_table('tags')
    # ### end Alembic commands ###
