"""phase 6: journal screenshot path

Revision ID: 56abdd0ae61b
Revises: 373ad0c2dfcf
Create Date: 2026-08-28 23:45:00.992338
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '56abdd0ae61b'
down_revision: str | None = '373ad0c2dfcf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('screenshot_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entries', 'screenshot_path')
    # ### end Alembic commands ###
